# Generated by Django 3.1 on 2020-08-28 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cochecito', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automovil',
            options={'verbose_name': 'Automovil'},
        ),
        migrations.RenameField(
            model_name='automovil',
            old_name='patente',
            new_name='placa',
        ),
    ]
