# Generated by Django 3.1 on 2020-08-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cochecito', '0003_auto_20200827_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovil',
            name='imagen',
            field=models.ImageField(null=True, upload_to='automoviles'),
        ),
    ]
